#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
gen_config.py — 由 templates/config.yaml 生成 LaTeX 参数文件
  输出: templates/config-class.tex  (\PassOptionsToClass，须在 \documentclass 前 \input)
        templates/config.tex        (geometry 版面与全部文本参数宏)
用法: python gen_config.py [templates目录]      默认取本脚本同级 ../templates
依赖: 无第三方依赖（优先使用 PyYAML，缺失时退回内置单行解析器）。
"""
import os
import sys

def load_config(path):
    """读取扁平的 key: value 配置。优先 PyYAML，缺失时用简易解析器。"""
    try:
        import yaml  # type: ignore
        with open(path, encoding="utf-8") as f:
            data = yaml.safe_load(f)
        return {k: str(v) for k, v in (data or {}).items()}
    except ImportError:
        data = {}
        with open(path, encoding="utf-8") as f:
            for line in f:
                line = line.rstrip("\n")
                s = line.strip()
                if not s or s.startswith("#"):
                    continue
                if ":" not in s:
                    continue
                key, _, val = s.partition(":")
                val = val.split(" #", 1)[0].strip()
                if len(val) >= 2 and val[0] == val[-1] == '"':
                    val = val[1:-1]
                data[key.strip()] = val
        return data

def esc(v):
    """转义 LaTeX 文本参数中少数危险字符（配置均为受信文本，仅做最小处理）。"""
    return v.replace("%", r"\%")

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    tdir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(script_dir, "..", "templates")
    tdir = os.path.abspath(tdir)
    cfg = load_config(os.path.join(tdir, "config.yaml"))

    banner = ("% Auto-generated by scripts/gen_config.py from config.yaml\n"
              "% 请勿手改本文件；修改 config.yaml 后重新运行 gen_config.py。\n")

    # ---- config-class.tex：\documentclass 之前的选项注入 ----
    class_tex = banner + "\\PassOptionsToClass{%s}{ctexart}\n" % esc(cfg.get("font_size", "12pt"))

    # ---- config.tex：geometry 与文本参数 ----
    geo_keys = ["paperwidth", "paperheight", "orientation", "margin_top",
                "margin_bottom", "margin_left", "margin_right", "headheight"]
    geo_map = {"margin_top": "top", "margin_bottom": "bottom",
               "margin_left": "left", "margin_right": "right"}
    opts = []
    for k in geo_keys:
        if k not in cfg:
            continue
        if k == "orientation":
            opts.append(cfg[k])  # landscape / portrait 为无值选项
        else:
            opts.append("%s=%s" % (geo_map.get(k, k), cfg[k]))
    geometry = "\\usepackage[\n  " + ",\n  ".join(opts) + "\n]{geometry}\n"

    text_keys = ["columns", "main_title", "teacher_head_left"]
    defaults = {"columns": "2"}
    def csname(k):  # 下划线转 CamelCase（@ 在导言区不是字母，不可用）
        return "pd" + "".join(w.capitalize() for w in k.split("_"))
    macros = []
    for k in text_keys:
        val = cfg.get(k, defaults.get(k, ""))
        macros.append("\\providecommand{\\%s}{%s}" % (csname(k), esc(val)))

    config_tex = (banner + "\n% --- 纸张与版面几何 ---\n" + geometry
                  + "\n% --- 文本参数 (\\pd<Key>) ---\n" + "\n".join(macros) + "\n")

    for name, content in [("config-class.tex", class_tex), ("config.tex", config_tex)]:
        out = os.path.join(tdir, name)
        old = open(out, encoding="utf-8").read() if os.path.exists(out) else None
        if old == content:
            print("[gen_config] %s 无变化" % name)
        else:
            with open(out, "w", encoding="utf-8") as f:
                f.write(content)
            print("[gen_config] 已生成 %s" % out)

if __name__ == "__main__":
    main()
